---
- name: install nginx packages
  package:
    name: '{{ nginx_packages }}'
    state: present

- name: set up /var/www/tmp
  file:
    path: /var/www/tmp
    state: directory
    mode: '0777'
    owner: www
    group: www

- name: create nginx directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  with_items: ["configs", "sites-available", "sites-enabled"]

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx

- name: copy nginx sub-configs
  copy:
    src: configs/
    dest: /etc/nginx/configs/
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx

- name: enable nginx
  service:
    name: nginx
    enabled: true

- name: flush_handlers
  meta: flush_handlers
