#!/bin/ksh
#
# {{ ansible_managed }}

daemon="/usr/local/libexec/nginx-ldap-auth/nginx-ldap-auth-daemon.py"

. /etc/rc.d/rc.subr

rc_start() {
	${rc_exec} "/usr/local/bin/python3 ${daemon}"
}

pexp="python3 ${daemon}"

rc_bg=YES
rc_reload=NO
rc_cmd $1
